name: Run Python script
on: [push]
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Python script
        run: python heart.py
